### ISSUE TITLE
curl: hard-coded CURLOPT_SSL_VERIFYPEER

### ISSUE THREAD

**Issue by hranicka** [Markette/GopaySimple#1]
In the code there is hard-coded `CURLOPT_SSL_VERIFYPEER` directive: 
https://github.com/Markette/GopaySimple/blob/master/src/GopaySimple.php#L110

It should be removed and rewritten the way of explicit configuration.

a.
I think the simplest way will be `public $curlOptions = []` property.
There I can set eg. `$gopay->curlOptions[] = [CURLOPT_SSL_VERIFYPEER = FALSE]` if I haven't certificates installed on my server and prefer currently hard-coded unsecure way.

b.
Better but longer way will be usage of some Curl wrapper instead of hard-coded curl calls.
I mean custom simple wrapper directly in the library or external library like https://packagist.org/packages/guzzlehttp/guzzle, https://packagist.org/packages/phpwrapper/curl, ...

Should I create a PR?

**Comment by f3l1x** [comment]
I get your point. I prefer no dependencies in this case.

So, choice a.

I handle it by my self, thank you. :)

I let you know.

**Comment by f3l1x** [comment]
Solved. 

Take a look at usage: https://github.com/Markette/GopaySimple/blob/f8dab1354891d37dc2539a30661f6dc9ffbfc9f9/tests/cases/GopaySimple.headers.phpt#L36-L49

It overrides defined options. In your case, `$gopay->options[CURLOPT_SSL_VERIFYPEER] = FALSE`.

**Comment by hranicka** [comment]
Thank you! :)

But option `CURLOPT_SSL_VERIFYPEER = FALSE` is still default and I think it should not be (it's unsafe - MITM).

**Comment by f3l1x** [comment]
@hranicka Oh, my fault. Now should be fixed. :-)

**Comment by hranicka** [comment]
:+1: Thank you! :)

Have a nice day and happy 2016 :-)
